@startuml sequencedemo
actor User as Foo
participant "Finance App" as Foo2
database Database as Foo3
Foo -> Foo2: HTTP request
Foo2 -> Foo3: SQL request
Foo3 --> Foo2: SQL response
Foo2 --> Foo: HTTP response
autonumber 1.1
Foo -> Foo2: HTTP request
Foo2 -> Foo3: SQL request
Foo3 --> Foo2: SQL response
Foo2 --> Foo: HTTP response
autonumber inc A
Foo -> Foo2: Authentication request
Foo2 --> Foo: Authentication response
Foo -> Foo2: HTTP request
note left: we are sending an HTTP request 
Foo2 -> Foo3: SQL request
note right 
we are making a 
request to the database
end note
Foo3 --> Foo2: SQL response
Foo2 --> Foo: HTTP response
autonumber inc A
Foo -> Foo2: Authentication request
alt valid credentials
Foo2 --> Foo: Authentication success
else wrong credentials
Foo2 --> Foo: Invalid credentials
end
@enduml