@startuml sequencedemo
User -> Server: HTTP request
Server -> DB: SQL request
DB --> Server: SQL response
Server --> User: HTTP response
@enduml

@startuml sequencedemo2
actor User as Foo
participant "Finance App" as Foo2
database Database as Foo3
autonumber "<b>."
autonumber 1.1
Foo -[#red]> Foo2: HTTP request
note left: we are sending an HTTP request 
Foo2 -> Foo3: SQL request
note right 
we are making a 
request to the database
end note
Foo3 --> Foo2: SQL response
Foo2 --> Foo: HTTP response
autonumber inc A
Foo -> Foo2: Authentication request
alt valid credentials
Foo2 --> Foo: Authentication success
else wrong credentials
Foo2 --> Foo: Invalid credentials
end
Foo2 --> Foo: Authentication response
@enduml


@startuml sequencedemo3
actor User as Foo
participant "Finance App" as Foo2
database Database as Foo3
autonumber "<b>."
autonumber 1.1
Foo -[#red]> Foo2: HTTP request
note left: we are sending an HTTP request 
Foo2 -> Foo3: SQL request
note right 
we are making a 
request to the database
end note
Foo3 --> Foo2: SQL response
Foo2 --> Foo: HTTP response
autonumber inc A
Foo -> Foo2: Authentication request
alt valid credentials
Foo2 --> Foo: Authentication success
else wrong credentials
Foo2 --> Foo: Authentication failure
group forgot password
Foo -> Foo2: Request forgot password
Foo2 --> Foo: Sent forgot password OTP
end
else server timeout
loop 3 times
Foo -> Foo2: Ping server
end
Foo2 --> Foo: Server available
end
Foo2 --> Foo: Authentication response
@enduml
